// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: token/grant_hash.proto

package token

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GrantHash is the SHA-256 digest of a grant's exact bytes, with no salt and
// no key derivation: the form in which a principal's outstanding grant is
// held.
type GrantHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bytes         []byte                 `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantHash) Reset() {
	*x = GrantHash{}
	mi := &file_token_grant_hash_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantHash) ProtoMessage() {}

func (x *GrantHash) ProtoReflect() protoreflect.Message {
	mi := &file_token_grant_hash_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantHash.ProtoReflect.Descriptor instead.
func (*GrantHash) Descriptor() ([]byte, []int) {
	return file_token_grant_hash_proto_rawDescGZIP(), []int{0}
}

func (x *GrantHash) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

var File_token_grant_hash_proto protoreflect.FileDescriptor

const file_token_grant_hash_proto_rawDesc = "" +
	"\n" +
	"\x16token/grant_hash.proto\x12\x05token\"!\n" +
	"\tGrantHash\x12\x14\n" +
	"\x05bytes\x18\x01 \x01(\fR\x05bytesBr\n" +
	"\tcom.tokenB\x0eGrantHashProtoP\x01Z!github.com/authaas/token-go;token\xa2\x02\x03TXX\xaa\x02\x05Token\xca\x02\x05Token\xe2\x02\x11Token\\GPBMetadata\xea\x02\x05Tokenb\x06proto3"

var (
	file_token_grant_hash_proto_rawDescOnce sync.Once
	file_token_grant_hash_proto_rawDescData []byte
)

func file_token_grant_hash_proto_rawDescGZIP() []byte {
	file_token_grant_hash_proto_rawDescOnce.Do(func() {
		file_token_grant_hash_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_grant_hash_proto_rawDesc), len(file_token_grant_hash_proto_rawDesc)))
	})
	return file_token_grant_hash_proto_rawDescData
}

var file_token_grant_hash_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_token_grant_hash_proto_goTypes = []any{
	(*GrantHash)(nil), // 0: token.GrantHash
}
var file_token_grant_hash_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_token_grant_hash_proto_init() }
func file_token_grant_hash_proto_init() {
	if File_token_grant_hash_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_grant_hash_proto_rawDesc), len(file_token_grant_hash_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_grant_hash_proto_goTypes,
		DependencyIndexes: file_token_grant_hash_proto_depIdxs,
		MessageInfos:      file_token_grant_hash_proto_msgTypes,
	}.Build()
	File_token_grant_hash_proto = out.File
	file_token_grant_hash_proto_goTypes = nil
	file_token_grant_hash_proto_depIdxs = nil
}
