// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: token/proof.proto

package token

import (
	identity "buf.build/gen/go/authaas/identity/protocolbuffers/go/identity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Proof is a principal and the grant issued to it: what a completed
// authentication returns, and what is presented to exchange for a token.
type Proof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Principal     *identity.Principal    `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Grant         *Grant                 `protobuf:"bytes,2,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proof) Reset() {
	*x = Proof{}
	mi := &file_token_proof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proof) ProtoMessage() {}

func (x *Proof) ProtoReflect() protoreflect.Message {
	mi := &file_token_proof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proof.ProtoReflect.Descriptor instead.
func (*Proof) Descriptor() ([]byte, []int) {
	return file_token_proof_proto_rawDescGZIP(), []int{0}
}

func (x *Proof) GetPrincipal() *identity.Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *Proof) GetGrant() *Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

var File_token_proof_proto protoreflect.FileDescriptor

const file_token_proof_proto_rawDesc = "" +
	"\n" +
	"\x11token/proof.proto\x12\x05token\x1a\x18identity/principal.proto\x1a\x11token/grant.proto\"^\n" +
	"\x05Proof\x121\n" +
	"\tprincipal\x18\x01 \x01(\v2\x13.identity.PrincipalR\tprincipal\x12\"\n" +
	"\x05grant\x18\x02 \x01(\v2\f.token.GrantR\x05grantBn\n" +
	"\tcom.tokenB\n" +
	"ProofProtoP\x01Z!github.com/authaas/token-go;token\xa2\x02\x03TXX\xaa\x02\x05Token\xca\x02\x05Token\xe2\x02\x11Token\\GPBMetadata\xea\x02\x05Tokenb\x06proto3"

var (
	file_token_proof_proto_rawDescOnce sync.Once
	file_token_proof_proto_rawDescData []byte
)

func file_token_proof_proto_rawDescGZIP() []byte {
	file_token_proof_proto_rawDescOnce.Do(func() {
		file_token_proof_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_proof_proto_rawDesc), len(file_token_proof_proto_rawDesc)))
	})
	return file_token_proof_proto_rawDescData
}

var file_token_proof_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_token_proof_proto_goTypes = []any{
	(*Proof)(nil),              // 0: token.Proof
	(*identity.Principal)(nil), // 1: identity.Principal
	(*Grant)(nil),              // 2: token.Grant
}
var file_token_proof_proto_depIdxs = []int32{
	1, // 0: token.Proof.principal:type_name -> identity.Principal
	2, // 1: token.Proof.grant:type_name -> token.Grant
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_token_proof_proto_init() }
func file_token_proof_proto_init() {
	if File_token_proof_proto != nil {
		return
	}
	file_token_grant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_proof_proto_rawDesc), len(file_token_proof_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_proof_proto_goTypes,
		DependencyIndexes: file_token_proof_proto_depIdxs,
		MessageInfos:      file_token_proof_proto_msgTypes,
	}.Build()
	File_token_proof_proto = out.File
	file_token_proof_proto_goTypes = nil
	file_token_proof_proto_depIdxs = nil
}
