name: CD

run-name: Publish ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
      - '!v*'

jobs:
  release:
    permissions:
      contents: write
    uses: katastroma/skeuotheke/.github/workflows/release-tag.yaml@v0
